name: CLOUDWAYS DEVELOPMENT WITH SFTP

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
    types:
      - closed
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SFTP upload
        uses: Dylan700/sftp-upload-action@latest
        with:
          server: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.DEV_SSH_USERNAME }}
          key: ${{ secrets.DEV_SSH_KEY }}
          uploads: |
            - source: "./"
              target: "/public_html"

      - name: Executing Linux Commands
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.DEV_SSH_USERNAME }}
          port: 22
          password: ${{ secrets.DEV_SSH_PASS }}
          key: ${{ secrets.DEV_SSH_KEY }}
          script: |
            cd ./public_html
            echo "creating env file...."
            php -r "file_exists('.env') || copy('.env.example', '.env');"

            echo "executing composer install...."
            composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
            #echo "Generating key..."
            #php artisan key:generate
            #echo "running migration"
            php artisan migrate
            #echo "run seed"
            #php artisan db:seed

            php ./artisan optimize:clear
            echo "done...."
